version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    environment:
        - ADAFRUIT_IO_KEY=${ADAFRUIT_IO_KEY}
    command: > 
      bash -c "echo \"Environment variable ${ADAFRUIT_IO_KEY}\" 
      && pip install --upgrade -r requirements.txt
      && pip install psycopg2-binary
      && python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py makemigrations app
      && python3 manage.py migrate app
      && python3 manage.py loaddata db.json
      && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
