# Generated by Django 2.0.4 on 2018-05-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll_worker',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
        migrations.AlterField(
            model_name='poll_worker',
            name='precinct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Precinct'),
        ),
    ]
