# Generated by Django 2.0.3 on 2018-04-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180331_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='ballot',
        ),
        migrations.AddField(
            model_name='ballot',
            name='measures',
            field=models.ManyToManyField(to='app.Measure'),
        ),
        migrations.AlterField(
            model_name='election',
            name='type',
            field=models.CharField(choices=[('G', 'general'), ('P', 'primary')], max_length=1),
        ),
    ]
